version: 2

# Build environment
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

# Optional: build Sphinx using the 'docs' folder
sphinx:
  configuration: docs/source/conf.py
